### ISSUE TITLE
The Final Descent - Bloodskal Blade - Stage 30

### ISSUE THREAD

**Issue by fadern** [Arthmoor/AFKTrack#11]
Hi,
USSE :  4.2.6a
Quest : The Final Descent, stage 30.
I have just experienced the bug were the Bloodskal Blade are not able to emit the ribbons of energy. I believe that it was fixed in v 4.1.7. 
I tried to use the command "player.setav rightitemcharge 99999" but it didnt work. The equipspell did...

**Comment by Arthmoor** [comment]
This isn't for reporting game bugs. That needs to be done here: https://afktrack.afkmods.com/
