### ISSUE TITLE
Cait's quest will not activate

### ISSUE THREAD

**Issue by acrossthestars07** [Arthmoor/AFKTrack#7]
I hope I'm posting this in the right place. Your directions on where to post didn't have a shortcut link, and the directions were vague. 
I encountered this issue around 200+ hours into my game. I was at Abernathy Farm. Cait asked to talk to me. She had already shared with me her first dialogue about how she grew up, (a couple hours prior.) So when I accepted the dialogue option to talk to her currently, Cait repeated the first dialogue about how she was raised, then went right into her second dialogue about being addicted to psycho. After I completed this dialogue, the quest, (Benign....something...) didn't pop up. In her dialogue she said to go to vault 95, which I had already cleared. I took her back there with me and cleared it out again. When we got to the room where she's supposed to get cured, nothing happens.  Cait just walks around making the same generalized comments. 
I've tried further raising my affinity with Cait, but her request to talk has not pooped up again. When I ask her what she thinks about the relationship, she responds with the same 3-4 phrases, (all positive.) 
Please let me know if there is anything else you need from me. 
Thanks so much!

**Comment by Arthmoor** [comment]
This needs to be posted at the tracker, not the issues section for the software itself.

https://afktrack.iguanadons.net/
