### ISSUE TITLE
Cannot purchase Vlindrel Hall in Markartj

### ISSUE THREAD

**Issue by Th4Sup3rce11** [Arthmoor/AFKTrack#9]
Apparently this is a semi-common bug. I believe it occurred somewhere along the civil war quest line. My character has aligned with the empire and is far past the point of trying to re-load a save. The dialogue option with the steward, Raerek, is limited to just “I’m looking for work”. The option to purchase a house in the city or any other dialogue options are not available and I was wondering if there is a fix for this.

**Comment by Arthmoor** [comment]
This isn't for reporting game bugs. That needs to be done here: https://afktrack.afkmods.com/
